// let idade = 20;
// let preco = 120.5;
// let nome = "pedro"
// let sobrenome = "santos"
// console.log("meu nome é",nome,""+ sobrenome,"e tenho",idade,"anos")

// console.log("minha idade e", idade);
// console.log("o preco e", preco);

function nome(){
return "pedro"

}

function sobreNome(){
    return "santos"
}
function anos(){
    return 19
}
 function trabalho(){
    return "desenvolvedor"
 }

let id = nome()
let name2 = sobreNome()
let idade = anos()
let profissao = trabalho()

console.log("meu nome é",id,name2,",","tenho", idade,"anos", "e sou",profissao)
